name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./rust
      run: cargo test --verbose
      
    - name: Setup Deno
      # uses: denoland/setup-deno@v1
      uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
      with:
        deno-version: v1.x

    # Uncomment this step to verify the use of 'deno fmt' on each commit.
    # - name: Verify formatting
    #   run: deno fmt --check

    - name: Run tests
      run: deno test -A --unstable
